swagger: '2.0'
info:
  description: Data Hub API
  version: 1.0.0
  title: Data Hub API
  contact:
    email: jim.smith@digital.trade.gov.uk
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

